giovvbat/valoris

- .gitignore
- mvnw
- mvnw.cmd
- pom.xml
- src/main/java/br/ufrn/imd/valoris/ValorisApplication.java
- src/main/java/br/ufrn/imd/valoris/controller/ContaController.java
- src/main/java/br/ufrn/imd/valoris/dao/ContaDao.java
- src/main/java/br/ufrn/imd/valoris/model/ContaModel.java
- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
- src/main/resources/application.yml
- src/test/java/br/ufrn/imd/valoris/ValorisApplicationTests.java
este PR é referente à issue 1 (Resolves #1)
> implementação da estrutura inicial do projeto + dao

- .gitignore
- mvnw
- mvnw.cmd
- pom.xml
- src/main/java/br/ufrn/imd/valoris/ValorisApplication.java
- src/main/java/br/ufrn/imd/valoris/controller/ContaController.java
- src/main/java/br/ufrn/imd/valoris/dao/ContaDao.java
- src/main/java/br/ufrn/imd/valoris/model/ContaModel.java
- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
- src/main/resources/application.yml
- src/test/java/br/ufrn/imd/valoris/ValorisApplicationTests.java
PR referente à branch que implementa a issue #1
> implementação da estrutura inicial do projeto + dao de conta (#1)

- src/main/java/br/ufrn/imd/valoris/controller/ContaController.java
- src/main/java/br/ufrn/imd/valoris/dto/ContaDTO.java
- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
> implementação de cadastrar conta (#2)

- src/main/java/br/ufrn/imd/valoris/controller/ContaController.java
- src/main/java/br/ufrn/imd/valoris/dto/TransacaoDTO.java
- src/main/java/br/ufrn/imd/valoris/exception/ResourceNotFoundException.java
- src/main/java/br/ufrn/imd/valoris/model/ContaModel.java
- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
> implementação de realizar débito (#5)

- src/main/java/br/ufrn/imd/valoris/controller/ContaController.java
- src/main/java/br/ufrn/imd/valoris/model/ContaModel.java
- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
> implementação de realizar crédito (#4)

- src/main/java/br/ufrn/imd/valoris/controller/ContaController.java
- src/main/java/br/ufrn/imd/valoris/dto/TransferenciaDTO.java
- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
> implementação da transferencia entre contas (#6)

- src/main/java/br/ufrn/imd/valoris/controller/ContaController.java
- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
> implementação de consultar saldo (#3)

- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
> corrigindo mensagem de ResourceNotFoundException (#14)

- src/main/java/br/ufrn/imd/valoris/dto/RespostaApiDTO.java
- src/main/java/br/ufrn/imd/valoris/handler/GlobalExceptionHandler.java
- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
PR referente à issue 17 (Resolves #17)
> implementacao do tratamento de excecoes (#17)

- src/main/java/br/ufrn/imd/valoris/exception/ResourceAlreadyExistsException.java
- src/main/java/br/ufrn/imd/valoris/exception/ResourceNotFoundException.java
- src/main/java/br/ufrn/imd/valoris/handler/GlobalExceptionHandler.java
- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
PR referente à issue 19 (Resolves #19)
> resolvendo bug de duplicacao de contas (#19)

- pom.xml
> corrigindo bug de compilação no `maven` (#27)

- README.md
> atualização do README.md (#21)

- src/main/java/br/ufrn/imd/valoris/exception/NotEnoughAccountBalanceException.java
- src/main/java/br/ufrn/imd/valoris/handler/GlobalExceptionHandler.java
- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
PR referente à issue 22 (Resolves #22 )
> implementando a correção de bug com saldo negativo (#22)

- src/main/java/br/ufrn/imd/valoris/dto/ContaDTO.java
- src/main/java/br/ufrn/imd/valoris/enums/TipoConta.java
- src/main/java/br/ufrn/imd/valoris/model/ContaBonusModel.java
- src/main/java/br/ufrn/imd/valoris/model/ContaModel.java
- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
PR referente à issue 23 (Resolves #23)
> implementação da conta bônus (#23)

- src/main/java/br/ufrn/imd/valoris/controller/ContaController.java
- src/main/java/br/ufrn/imd/valoris/dto/RenderJurosDTO.java
- src/main/java/br/ufrn/imd/valoris/enums/TipoConta.java
- src/main/java/br/ufrn/imd/valoris/exception/OperacaoInvalidaException.java
- src/main/java/br/ufrn/imd/valoris/handler/GlobalExceptionHandler.java
- src/main/java/br/ufrn/imd/valoris/model/ContaPoupancaModel.java
- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
> implementação da conta poupanca (#24)

- src/main/java/br/ufrn/imd/valoris/dto/TransacaoDTO.java
- src/main/java/br/ufrn/imd/valoris/dto/TransferenciaDTO.java
- src/main/java/br/ufrn/imd/valoris/handler/GlobalExceptionHandler.java
- src/main/java/br/ufrn/imd/valoris/model/ContaModel.java
> correção de bug com valores de operações negativos (#25)

- src/main/java/br/ufrn/imd/valoris/controller/ContaController.java
- src/main/java/br/ufrn/imd/valoris/dao/ContaDao.java
- src/main/java/br/ufrn/imd/valoris/exception/OperacaoInvalidaException.java
- src/main/java/br/ufrn/imd/valoris/handler/GlobalExceptionHandler.java
- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
> correção de implementação de conta poupança (#34)

- .gitignore
- mvnw
- mvnw.cmd
- pom.xml
- src/main/java/br/ufrn/imd/valoris/ValorisApplication.java
- src/main/java/br/ufrn/imd/valoris/controller/ContaController.java
- src/main/java/br/ufrn/imd/valoris/dao/ContaDao.java
- src/main/java/br/ufrn/imd/valoris/dto/ContaDTO.java
- src/main/java/br/ufrn/imd/valoris/dto/RespostaApiDTO.java
- src/main/java/br/ufrn/imd/valoris/dto/TransacaoDTO.java
- src/main/java/br/ufrn/imd/valoris/dto/TransferenciaDTO.java
- src/main/java/br/ufrn/imd/valoris/exception/NotEnoughAccountBalanceException.java
- src/main/java/br/ufrn/imd/valoris/exception/ResourceAlreadyExistsException.java
- src/main/java/br/ufrn/imd/valoris/exception/ResourceNotFoundException.java
- src/main/java/br/ufrn/imd/valoris/handler/GlobalExceptionHandler.java
- src/main/java/br/ufrn/imd/valoris/model/ContaModel.java
- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
- src/main/resources/application.yml
- src/test/java/br/ufrn/imd/valoris/ValorisApplicationTests.java
> liberando v1 para produção (#26)

- pom.xml
- src/main/java/br/ufrn/imd/valoris/dto/TransacaoDTO.java
- src/main/java/br/ufrn/imd/valoris/dto/TransferenciaDTO.java
- src/main/java/br/ufrn/imd/valoris/exception/NotEnoughAccountBalanceException.java
- src/main/java/br/ufrn/imd/valoris/handler/GlobalExceptionHandler.java
- src/main/java/br/ufrn/imd/valoris/model/ContaModel.java
- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
> trazendo a estabilização da v1 para a main (#37)

- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
PR referente à issue 44 (Resolves #44)
> implementando aprimoramento no cadastro de conta (#44)

- src/main/java/br/ufrn/imd/valoris/dto/ContaDTO.java
- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
> correção na criação de contas simples para exigir saldo inicial (#48)

- src/main/java/br/ufrn/imd/valoris/dao/ContaDao.java
- src/main/java/br/ufrn/imd/valoris/dto/ContaDTO.java
- src/main/java/br/ufrn/imd/valoris/exception/InitialBalanceMissingException.java
- src/main/java/br/ufrn/imd/valoris/handler/GlobalExceptionHandler.java
- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
> integrando mudanças de 'production' em 'staging' (#50)

- README.md
- src/main/java/br/ufrn/imd/valoris/controller/ContaController.java
- src/main/java/br/ufrn/imd/valoris/dao/ContaDao.java
- src/main/java/br/ufrn/imd/valoris/dto/ContaDTO.java
- src/main/java/br/ufrn/imd/valoris/dto/RenderJurosDTO.java
- src/main/java/br/ufrn/imd/valoris/enums/TipoConta.java
- src/main/java/br/ufrn/imd/valoris/exception/InitialBalanceMissingException.java
- src/main/java/br/ufrn/imd/valoris/handler/GlobalExceptionHandler.java
- src/main/java/br/ufrn/imd/valoris/model/ContaBonusModel.java
- src/main/java/br/ufrn/imd/valoris/model/ContaModel.java
- src/main/java/br/ufrn/imd/valoris/model/ContaPoupancaModel.java
- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
> liberando a versão v2.2 para produção (#54)

- src/main/java/br/ufrn/imd/valoris/dao/ContaDao.java
- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
> trazendo a estabilização da v2 para a main (#56) 

- src/main/java/br/ufrn/imd/valoris/controller/ContaController.java
- src/main/java/br/ufrn/imd/valoris/dao/ContaDao.java
- src/main/java/br/ufrn/imd/valoris/model/ContaModel.java
- src/main/java/br/ufrn/imd/valoris/model/ContaPoupancaModel.java
- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
PR referente à issue 60 (Resolves #60)
> implementação das funcionalidades para consulta de conta(s) (#60)

- src/main/java/br/ufrn/imd/valoris/model/ContaModel.java
- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
- src/test/java/br/ufrn/imd/valoris/service/ContaServiceTest.java
PR referente à issue 62 (Resolves #62)
> implementando testes unitários para consulta de saldo (#62)

- src/main/java/br/ufrn/imd/valoris/model/ContaBonusModel.java
- src/main/java/br/ufrn/imd/valoris/model/ContaPoupancaModel.java
- src/test/java/br/ufrn/imd/valoris/service/ContaServiceTest.java
> implementando testes unitários para consulta de conta (#66)

- src/test/java/br/ufrn/imd/valoris/service/ContaServiceTest.java
> implementando testes unitários para rendimento de juros (#73)

- src/test/java/br/ufrn/imd/valoris/service/ContaServiceTest.java
> removendo verificações desnecessárias dos testes de débito (#82)

- src/main/java/br/ufrn/imd/valoris/controller/ContaController.java
- src/main/java/br/ufrn/imd/valoris/dao/ContaDao.java
- src/main/java/br/ufrn/imd/valoris/dto/ContaDTO.java
- src/main/java/br/ufrn/imd/valoris/dto/RenderJurosDTO.java
- src/main/java/br/ufrn/imd/valoris/dto/SaldoDTO.java
- src/main/java/br/ufrn/imd/valoris/dto/TransacaoDTO.java
- src/main/java/br/ufrn/imd/valoris/dto/TransferenciaDTO.java
- src/main/java/br/ufrn/imd/valoris/exception/InvalidAmountException.java
- src/main/java/br/ufrn/imd/valoris/model/ContaBonusModel.java
- src/main/java/br/ufrn/imd/valoris/model/ContaModel.java
- src/main/java/br/ufrn/imd/valoris/model/ContaPoupancaModel.java
- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
- src/test/java/br/ufrn/imd/valoris/service/ContaServiceTest.java
> liberando v3.2 para produção (#84)

- src/test/java/br/ufrn/imd/valoris/service/ContaServiceTest.java
> trazendo a estabilização da v3 para a main (#87)

- .github/workflows/main.yml
> implementando CI na main (#90)

- .github/workflows/production.yml
- Dockerfile
> implementando CI na production (#96)

- .github/workflows/main.yml
- .github/workflows/production.yml
- .github/workflows/staging.yml
- Dockerfile
- pom.xml
> liberando v3.3 para produção (#99)

- README.md
> modificando README (#97)

- README.md
> integrando mudanças de 'production' em 'staging' (#98)

- .github/workflows/production.yml
> corrigindo implementação de production.yml (#107)

- src/main/java/br/ufrn/imd/valoris/controller/ContaController.java
> corrigindo erro de sintaxe

- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
> introduzindo erro de lógica no método creditar (#121)

- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
> consertando o erro de lógica introduzido (#122)

- src/main/java/br/ufrn/imd/valoris/service/ContaService.java
> alterando saldo mínimo para conta bônus (#127)

- src/test/java/br/ufrn/imd/valoris/service/ContaServiceTest.java
> corrigindo testes da conta bônus (#129)
